# Generated by Django 5.1.2 on 2024-12-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('adventure', 'Adventure'), ('leisure', 'Leisure'), ('cultural', 'Cultural'), ('nature', 'Nature')], max_length=50)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
            ],
        ),
    ]
