# Generated by Django 5.1.2 on 2024-12-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip_app', '0002_usertrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrip',
            name='accommodation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usertrip',
            name='activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertrip',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertrip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
