# Generated by Django 5.1.2 on 2024-12-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip_app', '0008_remove_review_destination_remove_review_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='description',
            new_name='activities',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='category',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='available_dates',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='price',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='title',
        ),
        migrations.AddField(
            model_name='destination',
            name='available_dates',
            field=models.DateField(default='2024-12-31'),
        ),
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='UserTripCustomization',
        ),
    ]
