# Generated by Django 5.1.2 on 2024-12-30 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip_app', '0009_rename_description_trip_activities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='name',
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='trip_type',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('leisure', 'Leisure'), ('business', 'Business')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='accommodation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='available_dates',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='Trip_app.destination'),
        ),
    ]
