# Generated by Django 5.1.2 on 2024-12-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip_app', '0010_remove_destination_name_destination_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='available_dates',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='trip_type',
        ),
        migrations.AddField(
            model_name='destination',
            name='available_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='available_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Leisure', 'Leisure')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
