# Generated by Django 5.1.2 on 2024-12-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip_app', '0011_remove_destination_available_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='available_from',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='available_to',
            field=models.DateField(default='2024-12-31'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(default='Unknown Destination', max_length=100),
        ),
        migrations.AlterField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Leisure', 'Leisure')], default='Leisure', max_length=50),
        ),
    ]
