# Generated by Django 5.1.2 on 2024-12-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip_app', '0012_alter_destination_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='destination_images/default_image.jpg', upload_to='destination_images/'),
        ),
    ]
