# Generated by Django 5.1.2 on 2024-12-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip_app', '0013_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='itinerary',
            field=models.TextField(default='Itinerary details go here'),
        ),
        migrations.AddField(
            model_name='destination',
            name='reviews',
            field=models.TextField(default='No reviews yet.'),
        ),
    ]
