# Generated by Django 5.1.2 on 2024-12-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trip_app', '0017_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('meals_included', models.BooleanField(default=True)),
                ('accommodations', models.ManyToManyField(related_name='packages', to='Trip_app.accommodation')),
                ('activities', models.ManyToManyField(related_name='packages', to='Trip_app.activity')),
                ('destinations', models.ManyToManyField(related_name='packages', to='Trip_app.destination')),
            ],
        ),
    ]
