# Generated by Django 5.1.2 on 2024-12-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trip_app', '0019_packagebooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageBooking',
        ),
    ]
