# Generated by Django 5.1.2 on 2025-01-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trip_app', '0022_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
